# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Request" do
    optional :id, :int64, 1
  end
  add_message "Response" do
    optional :id, :int64, 1
  end
end

Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("Request").msgclass
Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("Response").msgclass
