# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: stream.proto for package ''

require 'grpc'
require 'concurrent'
require 'concurrent-edge'
require_relative 'stream_pb'

module Stream
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Stream'

    rpc :GetMessage, Request, stream(Response)
  end

  Stub = Service.rpc_stub_class
end

class RespEnumerator
  def initialize(queue)
    @queue = queue
  end

  def each
    return enum_for(:each) unless block_given?
    begin
      while 1
        yield Response.new(id: @queue.shift)
      end
    rescue StandardError => e
      fail e # signal completion via an error
    end
  end
end

class SimpleStream < Stream::Service
  def initialize(subscriptions)
    @subscriptions = subscriptions
  end

  def get_message(req, _)
    id = req.id
    queue = Queue.new
    @subscriptions << queue
    RespEnumerator.new(queue).each
  end
end
